### ISSUE TITLE
Crash bug

### ISSUE THREAD

**Issue by mopeneko** [enricocid/Music-Player-GO#127]
## Overview

The app crashes when the user doesn't have any music files.

## Log

```
java.util.NoSuchElementException: Collection is empty.
	at com.iven.musicplayergo.MainActivity.a(:35)
	at com.iven.musicplayergo.MainActivity.a(Unknown Source:6)
	at androidx.lifecycle.LiveData.a(:1)
	at androidx.lifecycle.LiveData.b(Unknown Source:44)
	at androidx.lifecycle.LiveData.b(Unknown Source:14)
	at f.o.m.b(Unknown Source:0)
	at f.p.a.b$a.a(:15)
	at f.p.b.c$e.handleMessage(:9)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loop(Unknown Source:242)
	at android.app.ActivityThread.main(Unknown Source:98)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:275)
```

## Environment

- Device: Xiaomi Mi 8 Lite
- OS: Android 10

**Comment by enricocid** [comment]
Is this an old version of the 4.0.x branch? LiveData is not used anymore in newer versions.
This crash has been already [addressed](https://github.com/enricocid/Music-Player-GO/commit/aa308c8281b83b7405745e62656b234b05719797) in 4.1.3 version which is still not available on f-droid (try the latest [APK](https://github.com/enricocid/Music-Player-GO/releases/tag/v4.1.4) to see if the problem is fixed) :)

**Comment by mopeneko** [comment]
Thank you for reading my issue.

Update to the lateat version and it is fixed.

**Comment by enricocid** [comment]
Hi, 
this issue is caused by the MediaStore query at boot. After many accesses the query returns different results producing crashes like this.
So I started adding a db to store music to reduce mediastore accesses.

Could please try this one and let me know if it works good?

https://drive.google.com/open?id=1uP87nBZ4T9O8nEHYIl1P8z0X1mmAdfAn

thanks
