### ISSUE TITLE
NumberFormatException while launching

### ISSUE THREAD

**Issue by dirk-olmes** [enricocid/Music-Player-GO#141]
When I launch it the player flashes up quickly but then terminates. I found the following exception in the logs:
```
FATAL EXCEPTION: main
Process: com.iven.musicplayergo, PID: 8534
c.d.b.w: java.lang.NumberFormatException: For input string: "Shrek Musical Soundtrack"
	at c.d.b.c0.b0.o$b.a(:1)
	at c.d.b.c0.b0.j$a.a(:1)
	at c.d.b.c0.b0.j$a.a(:1)
	at c.d.b.j.a(:7)
	at c.b.a.m.c(:1)
	at com.iven.musicplayergo.MainActivity.a(:35)
	at com.iven.musicplayergo.MainActivity.a(Unknown Source:6)
	at androidx.lifecycle.LiveData.a(:1)
	at androidx.lifecycle.LiveData.b(Unknown Source:44)
	at androidx.lifecycle.LiveData.b(Unknown Source:14)
	at g.o.o.b(Unknown Source:0)
	at g.p.a.b$a.a(:15)
	at g.p.b.c$c.run(:9)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NumberFormatException: For input string: "Shrek Musical Soundtrack"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at c.d.b.e0.a.n(Unknown Source:146)
	... 20 more```

The folder is in my Music folder along with a lot of others.

**Comment by enricocid** [comment]
Thanks for reporting. This issue was already reported from other users. It is generally fixed by uninstalling and reinstalling the app.
It is caused by the fact that the app accesses Mediastore every time it boots. 
To solve I'm implementing a database to store music reducing accesses but it require time before I can release it.

Try to uninstall/reinstall the app. 

I will post some test APK later this week so you can test the DB to see if this problem was solved :)

**Comment by dirk-olmes** [comment]
Thanks for your feedback. I reinstalled the app and it works again.
