### ISSUE TITLE
The app crashed when I tried to open it for the first time after installation.

### ISSUE THREAD

**Issue by sagorahmed** [enricocid/Music-Player-GO#62]
#### Actual behavior
After installing the app when I tried to open it for the first time by giving permission, suddenly the app crashed.

#### Expected behavior
The users should be able to open the app after installing it without crashing the app.

#### How to reproduce
1. Download the latest app from the play store.
2. Then open it.
3. Press "OK" when it will ask your access.
4. Then press "ALLOW" to give access to this app of photos, media, and files on your device.
5. See error.

* App version: V3.5.2.4
* Operating system: Android 6.0.1

#### Logcat
``` 
04-12 12:26:55.631  8390  8390 E AndroidRuntime: FATAL EXCEPTION: main

04-12 12:26:55.631  8390  8390 E AndroidRuntime: Process: com.iven.musicplayergo, PID: 8390

04-12 12:26:55.631  8390  8390 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=68124, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS VirtualScreenParam=Params{mDisplayId=-1, null, mFlags=0x00000000)} (has extras) }} to activity {com.iven.musicplayergo/com.iven.musicplayergo.MainActivity}: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

04-12 12:26:55.631  8390  8390 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4998)

04-12 12:26:55.631  8390  8390 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5041)

04-12 12:26:55.631  8390  8390 E AndroidRuntime: 	at android.app.ActivityThread.access$1600(ActivityThread.java:229)

04-12 12:26:55.631  8390  8390 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)

04-12 12:26:55.631  8390  8390 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)

04-12 12:26:55.631  8390  8390 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

04-12 12:26:55.631  8390  8390 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7325)

04-12 12:26:55.631  8390  8390 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

04-12 12:26:55.631  8390  8390 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)

04-12 12:26:55.631  8390  8390 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

04-12 12:26:55.631  8390  8390 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

04-12 12:26:55.631  8390  8390 E AndroidRuntime: 	at androidx.f.a.j.u(Unknown Source)

04-12 12:26:55.631  8390  8390 E AndroidRuntime: 	at androidx.f.a.j.a(Unknown Source)

04-12 12:26:55.631  8390  8390 E AndroidRuntime: 	at androidx.f.a.a.d(Unknown Source)

04-12 12:26:55.631  8390  8390 E AndroidRuntime: 	at com.iven.musicplayergo.MainActivity.g(Unknown Source)

04-12 12:26:55.631  8390  8390 E AndroidRuntime: 	at com.iven.musicplayergo.MainActivity.onRequestPermissionsResult(Unknown Source)

04-12 12:26:55.631  8390  8390 E AndroidRuntime: 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7291)

04-12 12:26:55.631  8390  8390 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:7169)

04-12 12:26:55.631  8390  8390 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4994)

04-12 12:26:55.631  8390  8390 E AndroidRuntime: 	... 9 more
```

**Comment by enricocid** [comment]
Thanks for the feedback, this is due to the fact I can't test the app on multiple Android versions.
Thanks for reporting, gonna fix asap

**Comment by enricocid** [comment]
Hello, here is the test apk

https://drive.google.com/file/d/11VDTdZp-J3kre547DbLFeVBKd0rlaYiL/view?usp=sharing

**Comment by sagorahmed** [comment]
Hi @enricocid 
This issue is not occurring anymore in the test version you provided. 
Good to see how passionate you about the open source project by fixing an issue in a very short time.
Thanks!

**Comment by enricocid** [comment]
Thanks :D
