### ISSUE TITLE
The app crashed when I tried to change a song from notification panel after closing it.

### ISSUE THREAD

**Issue by sagorahmed** [enricocid/Music-Player-GO#63]
#### Expected behavior
The users should be able to change songs from notification panel after exiting from the app.

#### Actual behavior
When I tried to change the song from notification panel after closing/exiting the app, then within a second the app crashes.

#### How to reproduce
1. Open the app.
2. Play a song.
3. Then exit from the app.
4. Pull down the notification panel of your phone.
5. Then try to change the song by pressing the next/previous button.
6. At last, pull up the notification panel and notice the error.

* App version: v3.5.2.5
* Operating system: Android 6.0.1

#### Recording Of The Bug
![musicgo](https://media.giphy.com/media/M8RCtWkYCzYL3VVMwd/giphy.gif)

#### LogCat
```
04-17 19:48:50.793 22796 22796 E AndroidRuntime: FATAL EXCEPTION: main

04-17 19:48:50.793 22796 22796 E AndroidRuntime: Process: com.iven.musicplayergo, PID: 22796

04-17 19:48:50.793 22796 22796 E AndroidRuntime: java.lang.IllegalStateException: Fragment a{b1192b3 (caf01c10-e2a5-4296-8dc1-95f783348c73)} not attached to a context.

04-17 19:48:50.793 22796 22796 E AndroidRuntime: 	at androidx.fragment.app.d.n(Unknown Source)

04-17 19:48:50.793 22796 22796 E AndroidRuntime: 	at androidx.fragment.app.d.a(Unknown Source)

04-17 19:48:50.793 22796 22796 E AndroidRuntime: 	at com.iven.musicplayergo.a.a(Unknown Source)

04-17 19:48:50.793 22796 22796 E AndroidRuntime: 	at com.iven.musicplayergo.a.c(Unknown Source)

04-17 19:48:50.793 22796 22796 E AndroidRuntime: 	at com.iven.musicplayergo.c.b.a(Unknown Source)

04-17 19:48:50.793 22796 22796 E AndroidRuntime: 	at com.iven.musicplayergo.c.b.onPrepared(Unknown Source)

04-17 19:48:50.793 22796 22796 E AndroidRuntime: 	at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:3712)

04-17 19:48:50.793 22796 22796 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)

04-17 19:48:50.793 22796 22796 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

04-17 19:48:50.793 22796 22796 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7325)

04-17 19:48:50.793 22796 22796 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

04-17 19:48:50.793 22796 22796 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)

04-17 19:48:50.793 22796 22796 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

04-17 19:48:50.823  2671 23060 E android.os.Debug: ro.product_ship = true

04-17 19:48:50.823  2671 23060 E android.os.Debug: ro.debug_level = 0x4f4c

04-17 19:48:50.823  2671 23060 E android.os.Debug: sys.mobilecare.preload = false
```

**Comment by enricocid** [comment]
Thanks for the report😁. Gonna post an APK asap!

**Comment by sagorahmed** [comment]
Thanks @enricocid

**Comment by enricocid** [comment]
Hello,

here is a test apk

https://drive.google.com/file/d/1j_Ff_WMTulhGSD3mDEX-rnUrbTtVeVzF/view?usp=sharing


Sorry for the late reply, but only today I was able to focus on this problem. Thanks

p.s. = thanks to the previous crash report I registered from gplay dev platform a -102% crashes. Thanks. :D

**Comment by enricocid** [comment]
@sagorahmed  should be fixed now

https://drive.google.com/open?id=18o72O0ldrQMTUuipw4gUgsmCVsv1vD1_
