### ISSUE TITLE
App crashed after granting storage permission

### ISSUE THREAD

**Issue by SandBlock4** [enricocid/Music-Player-GO#71]
After installing and launching the app, granting storage permission, the app crashed and will consistently crash if launched.

### Logcat
```
05-23 18:31:33.838 16652 16652 D AndroidRuntime: Shutting down VM
05-23 18:31:33.838 16652 16734 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
05-23 18:31:33.838 16652 16734 E AndroidRuntime: Process: com.iven.musicplayergo, PID: 16652
05-23 18:31:33.838 16652 16734 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
05-23 18:31:33.838 16652 16734 E AndroidRuntime:        at android.os.AsyncTask$3.done(AsyncTask.java:355)
05-23 18:31:33.838 16652 16734 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
05-23 18:31:33.838 16652 16734 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
05-23 18:31:33.838 16652 16734 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
05-23 18:31:33.838 16652 16734 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
05-23 18:31:33.838 16652 16734 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-23 18:31:33.838 16652 16734 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-23 18:31:33.838 16652 16734 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:784)
05-23 18:31:33.838 16652 16734 E AndroidRuntime: Caused by: java.lang.IllegalStateException: audioArtist must not be null
05-23 18:31:33.838 16652 16734 E AndroidRuntime:        at com.iven.musicplayergo.b.d$a.doInBackground(Unknown Source:129)
05-23 18:31:33.838 16652 16734 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:334)
05-23 18:31:33.838 16652 16734 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-23 18:31:33.838 16652 16734 E AndroidRuntime:        ... 4 more
05-23 18:31:33.838 16652 16652 E AndroidRuntime: FATAL EXCEPTION: main
05-23 18:31:33.838 16652 16652 E AndroidRuntime: Process: com.iven.musicplayergo, PID: 16652
05-23 18:31:33.838 16652 16652 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
05-23 18:31:33.838 16652 16652 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:534)
05-23 18:31:33.838 16652 16652 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
05-23 18:31:33.838 16652 16652 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
05-23 18:31:33.838 16652 16652 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-23 18:31:33.838 16652 16652 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
05-23 18:31:33.838 16652 16652 E AndroidRuntime:        ... 1 more
05-23 18:31:33.838 16652 16652 E AndroidRuntime: Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: audioArtist must not be null
05-23 18:31:33.838 16652 16652 E AndroidRuntime:        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
05-23 18:31:33.838 16652 16652 E AndroidRuntime:        at java.util.concurrent.FutureTask.get(FutureTask.java:193)
05-23 18:31:33.838 16652 16652 E AndroidRuntime:        at android.os.AsyncTask.get(AsyncTask.java:543)
05-23 18:31:33.838 16652 16652 E AndroidRuntime:        at com.iven.musicplayergo.b.d$b.<init>(Unknown Source:17)
05-23 18:31:33.838 16652 16652 E AndroidRuntime:        at com.iven.musicplayergo.b.d.a(Unknown Source:7)
05-23 18:31:33.838 16652 16652 E AndroidRuntime:        at com.iven.musicplayergo.a.J(Unknown Source:60)
05-23 18:31:33.838 16652 16652 E AndroidRuntime:        at com.iven.musicplayergo.a$e.onServiceConnected(Unknown Source:96)
05-23 18:31:33.838 16652 16652 E AndroidRuntime:        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1918)
05-23 18:31:33.838 16652 16652 E AndroidRuntime:        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1950)
05-23 18:31:33.838 16652 16652 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:891)
05-23 18:31:33.838 16652 16652 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
05-23 18:31:33.838 16652 16652 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:207)
05-23 18:31:33.838 16652 16652 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7539)
05-23 18:31:33.838 16652 16652 E AndroidRuntime:        ... 3 more
05-23 18:31:33.838 16652 16652 E AndroidRuntime: Caused by: java.lang.IllegalStateException: audioArtist must not be null
05-23 18:31:33.838 16652 16652 E AndroidRuntime:        at com.iven.musicplayergo.b.d$a.doInBackground(Unknown Source:129)
05-23 18:31:33.838 16652 16652 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:334)
05-23 18:31:33.838 16652 16652 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-23 18:31:33.838 16652 16652 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
05-23 18:31:33.838 16652 16652 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-23 18:31:33.838 16652 16652 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-23 18:31:33.838 16652 16652 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:784)
05-23 18:31:33.838 16652 16652 I Process : Sending signal. PID: 16652 SIG: 9
```

* Version: Fdroid 3.5.2.6
* OS: Android 9

**Comment by enricocid** [comment]
Thanks, I will solve as soon as I'll get a device running android 9 (i got my device stolen...)
