### ISSUE TITLE
Permission issue on Android Q

### ISSUE THREAD

**Issue by r2binx** [enricocid/Music-Player-GO#99]
Playback fails on Android Q even with storage access permission. Perhaps related to [scoped storage](https://developer.android.com/training/data-storage#scoped-storage)

`W/System.err: java.io.FileNotFoundException: /storage/14E8-1919/Music/01 - Picking Up Bags (Feat Tiny C Style) [Prod Cardo] (DatPiff Exclusive).mp3: open failed: EACCES (Permission denied)
        at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.FileInputStream.<init>(FileInputStream.java:159)
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1182)
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1160)
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1125)
        at com.iven.musicplayergo.player.MediaPlayerHolder.initMediaPlayer(MediaPlayerHolder.kt:298)
        at com.iven.musicplayergo.MainActivity.startPlayback(MainActivity.kt:659)
        at com.iven.musicplayergo.MainActivity.access$startPlayback(MainActivity.kt:56)
        at com.iven.musicplayergo.MainActivity$setAlbumSongs$3.invoke(MainActivity.kt:649)
        at com.iven.musicplayergo.MainActivity$setAlbumSongs$3.invoke(MainActivity.kt:56)
W/System.err:     at com.iven.musicplayergo.adapters.SongsAdapter$SongsHolder$bindItems$1.onClick(SongsAdapter.kt:54)
        at android.view.View.performClick(View.java:7125)
        at android.view.View.performClickInternal(View.java:7102)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27336)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
    Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err:     at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7255)
        at libcore.io.IoBridge.open(IoBridge.java:482)
    	... 21 more`

**Comment by enricocid** [comment]
Thanks for reporting. I will post test apk asap here as I don't have a device running android Q. :)
